//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceForMail.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbEntities : DbContext
    {
        public DbEntities()
            : base("name=DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MailInfo> MailInfos { get; set; }
    
        public virtual ObjectResult<CheckHDDSize_Setting_Result> CheckHDDSize_Setting(string line, string iP)
        {
            var lineParameter = line != null ?
                new ObjectParameter("Line", line) :
                new ObjectParameter("Line", typeof(string));
    
            var iPParameter = iP != null ?
                new ObjectParameter("IP", iP) :
                new ObjectParameter("IP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CheckHDDSize_Setting_Result>("CheckHDDSize_Setting", lineParameter, iPParameter);
        }
    
        public virtual ObjectResult<string> Public_Update_WatchDog(string line, string iP)
        {
            var lineParameter = line != null ?
                new ObjectParameter("Line", line) :
                new ObjectParameter("Line", typeof(string));
    
            var iPParameter = iP != null ?
                new ObjectParameter("IP", iP) :
                new ObjectParameter("IP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Public_Update_WatchDog", lineParameter, iPParameter);
        }
    
        public virtual ObjectResult<SW_Module_Path_Read_Result> SW_Module_Path_Read(string serverIP)
        {
            var serverIPParameter = serverIP != null ?
                new ObjectParameter("ServerIP", serverIP) :
                new ObjectParameter("ServerIP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SW_Module_Path_Read_Result>("SW_Module_Path_Read", serverIPParameter);
        }
    }
}
